extends: '.eslintrc.yaml'
env:
  es6: true
ecmaFeatures:
  arrowFunctions: true
  binaryLiterals: true
  blockBindings: true
  classes: true
  defaultParams: true
  destructuring: true
  forOf: true
  generators: true
  modules: true
  objectLiteralComputedProperties: true
  objectLiteralDuplicateProperties: true
  objectLiteralShorthandMethods: true
  objectLiteralShorthandProperties: true
  octalLiterals: true
  regexUFlag: true
  regexYFlag: true
  restParams: true
  spread: true
  superInFunctions: true
  templateStrings: true
  unicodeCodePointEscapes: true
  globalReturn: true
rules:
  # ECMAScript 6
  arrow-body-style:
    - 2
    - "as-needed"
  arrow-parens:
    - 2
    - "as-needed"
  arrow-spacing:
    - 2
    - before: true
      after: true
  constructor-super: 2
  generator-star-spacing:
    - 2
    - "before"
  no-arrow-condition: 2
  no-class-assign: 2
  no-const-assign: 2
  no-dupe-class-members: 2
  no-this-before-super: 2
  no-var: 2
  object-shorthand:
    - 2
    - "always"
  prefer-arrow-callback: 1
  prefer-const: 1
  prefer-reflect: 1
  prefer-spread: 2
  prefer-template: 2
  require-yield: 2
